# Default values for pwa-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ritchellegmp/pwa-test
  tag: 0.1.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080